services:
  - type: web
    name: stellar-bot
    runtime: node
    plan: free
    buildCommand: cd server && npm install && npm run prisma:generate && npm run build
    startCommand: cd server && node dist/index.js
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        scope: run
        isFile: false
      - key: DATABASE_URL
        value: file:./prod.db
        scope: run
      - key: PORT
        value: "4000"
        scope: run
      - key: NODE_ENV
        value: production
        scope: run
      - key: GOOGLE_SEARCH_API_KEY
        scope: run
        isFile: false
      - key: GOOGLE_SEARCH_CX
        scope: run
        isFile: false
      - key: OPENAI_API_KEY
        scope: run
        isFile: false
